remindWeb/config/routes.rb
Rails.application.routes.draw do
  root                  'welcome#index'
  get        'signup' => 'users#new'
  get        'login'  => 'sessions#new'
  post       'login'  => 'sessions#create'
  delete     'logout' => 'sessions#destroy'
  resources :users
end

remindWeb/app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token
	before_save { self.email = email.downcase }
	validates :name,  presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
					  format: { with: VALID_EMAIL_REGEX },
					  uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_token, User.digest(remember_token))
	end

	def authenticated?(remember_token)
		return false if remember_digest.nil?
	    BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	def forget
		update_attribute(:remember_token, nil)
	end
end

remindWeb/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

remindWeb/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
  		params[:session][:remember_me] == '1' ? remember(user) : forget(user)
  		redirect_back_to user
  	else
  		flash.now[:danger] = "Invalid email/password combination"
  		render 'new'
  	end
  end

  def destroy
  	log_out if logged_in?
  	redirect_to  root_url
  end
end

remindWeb/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user  = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		log_in @user
  		redirect_to @user
  		flash[:success] = "Welcome to the Remind"
  	else
  		render 'new'
  	end
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update_attributes(user_params)
  		flash[:success] = "You have successfully updated your profile"
  		redirect_to users_url
  	else
  		render 'edit'
  	end
  end

  private 
    def user_params
    	params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def logged_in_user
	    unless logged_in?
	    	store_location
	   		flash[:danger] = "Please log in"
			redirect_to login_url
		end
	end

	def correct_user
  		@user = User.find(params[:id])
  		redirect_to(root_url) unless current_user?(user)
  	end
end

remindWeb/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

remindWeb/app/helpers/application_helper.rb
module ApplicationHelper
end

remindWeb/app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		if (@user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	def current_user?(user)
		user == current_user
	end

	def forget
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	def redirect_back_or
		redirect_to(session[:forwarding_url] || default)
		session.delete(:forwarding_url)
	end

	def store_location
		session[:forwarding_url] = request.url if request.get?
	end
end

remindWeb/app/helpers/users_helper.rb
module UsersHelper
end

remindWeb/app/helpers/welcome_helper.rb
module WelcomeHelper
end

remindWeb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Remind</title>
  <link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container-ui">
		<div class="row">
			<div class="twelve column">
				<%= yield %>
			</div>
		</div>
	</div>
	<!--<%= debug(params) if Rails.env.development? %>-->

</body>
</html>

remindWeb/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div>
		The form contains <%= pluralize(@user.errors.count, "error") %>
		<ul>
			<%= @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

remindWeb/app/views/shared/_header.html.erb
<div>
	<div class="container">
		<div class="row">
			<%= link_to 'Remind', root_path, class: 'logo' %>
			<nav>
				<li><%= link_to "Signup", signup_path %></li>
				<li><%= link_to "Login", login_path %></li>
			</nav>
		</div>
	</div>
</div>

remindWeb/app/views/users/edit.html.erb
<div class="auth">
	<div class="form">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.email_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Save changes" %>
		<% end %>
	</div>
</div>

remindWeb/app/views/users/new.html.erb
<div class="head-auth">
	<%= render 'shared/header' %>
</div>

<div class="auth">
	<div class="form">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.email_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Create my account", class: "button-primary" %>
		<% end %>
	</div>
</div>

remindWeb/app/views/welcome/index.html.erb
<div class="index">
	<header>
		<%= render 'shared/header' %>
	</header>
	<div class="container">
		<div class="row">
			<div class="desc">
				<h1>Stay in control <br> of your time</h1>
				<%= link_to "Try Remind", signup_url, class: "button button-primary" %>
			</div>
		</div>
	</div>
</div>